/* eslint-disable jsx-a11y/anchor-is-valid */
import React from 'react';
import { makeStyles } from '@material-ui/core/styles';

import Box from '@material-ui/core/Box';
import Paper from '@material-ui/core/Paper';

import Link from 'components/Link';
import Button from 'components/Button';
import Typography from 'components/Typography';

import Layout from '../components/ContentLayout';

const useStyles = makeStyles(({ spacing }) => ({
  paper: {
    minWidth: 400,
    // height: '100%',
    // minHeight: '100%',
    padding: spacing(3, 4),
    display: 'flex',
    flexDirection: 'column',
  },
}));

const Home = () => {
  const classes = useStyles();

  return (
    <Layout>

      <Box
        px={3}
        py={4}
        color="common.white"
        bgcolor="primary.main"
        display="flex"
        justifyContent="space-between"
      >

        <Box>

          <Typography
            gutterBottom
            variant="subtitle"
            message="SIMULATION"
          />

          <Typography
            gutterBottom
            variant="h3"
            message="IoT Device Simulator"
          />

          <Typography
            gutterBottom
            variant="h5"
            message="virtual device simulation solution to evaluate IoT applications"
          />

          <Typography
            variant="body1"
            message="The IoT Device Simulator helps you easily build a pool of virtual devices to evaluate your IoT applications that gather, process, analyze and act on data generated by connected devices."
          />

        </Box>

        <Box width={32} />

        <Paper
          className={classes.paper}
        >
          <Typography
            gutterBottom
            variant="h6"
            message="My Devices"
          />

          <Typography
            gutterBottom
            variant="h4"
            message="0 Devices"
          />

          <Box
            display="flex"
          >

            <Button
              variant="contained"
              color="secondary"
              label="Create a Device Type"
            />

            <Box width={16} />

            <Button
              variant="contained"
              color="secondary"
              label="Create a Device"
            />

          </Box>

        </Paper>

      </Box>

      <Box
        p={3}
        display="flex"
        alignItems="flex-start"
        justifyContent="space-between"
      >

        <Box
          flex={1}
        >

          <Paper
            className={classes.paper}
          >
            <Typography
              gutterBottom
              variant="h6"
              message="About this Application"
            />

            <img alt="start" width="100%" src="/assets/img/iot-ds.png" />
          </Paper>

          <Box height={32} />

          <Paper
            className={classes.paper}
          >
            <Typography
              gutterBottom
              variant="h6"
              message="Getting Started"
            />

            <img alt="start" width="100%" src="/assets/img/iot-ds.png" />
          </Paper>

        </Box>

        <Box width={32} />

        <Paper
          className={classes.paper}
        >
          <Typography
            gutterBottom
            variant="h6"
            message="Documentation"
          />

          <Link
            href="#"
            gutterBottom
            variant="body1"
            label="Solution Overview"
          />

          <Link
            href="#"
            gutterBottom
            variant="body1"
            label="Solution Implementation Guide"
          />

          <Link
            href="#"
            gutterBottom
            variant="body1"
            label="GitHub Repository"
          />
        </Paper>

      </Box>

    </Layout>
  );
};

export default Home;
